-- upgrade --
ALTER TABLE "user" ALTER COLUMN "last_name" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "first_name" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "avatar" DROP NOT NULL;
ALTER TABLE "user" ALTER COLUMN "last_login" TYPE TIMESTAMPTZ USING "last_login"::TIMESTAMPTZ;
ALTER TABLE "user" ALTER COLUMN "last_login" DROP NOT NULL;
-- downgrade --
ALTER TABLE "user" ALTER COLUMN "last_name" SET NOT NULL;
ALTER TABLE "user" ALTER COLUMN "first_name" SET NOT NULL;
ALTER TABLE "user" ALTER COLUMN "avatar" SET NOT NULL;
ALTER TABLE "user" ALTER COLUMN "last_login" SET NOT NULL;
ALTER TABLE "user" ALTER COLUMN "last_login" TYPE TIMESTAMPTZ USING "last_login"::TIMESTAMPTZ;
